# Set Public Headers
set(pub_hdrs 
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/libclangex.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/CXError.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/CXTypes.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/AST/CXASTConsumer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/AST/CXASTContext.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/AST/CXDecl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/AST/CXDeclarationName.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/AST/CXDeclBase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/AST/CXDeclCXX.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/AST/CXDeclGroup.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/AST/CXDeclTemplate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/AST/CXNestedNameSpecifier.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/AST/CXTemplateBase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/AST/CXTemplateName.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/AST/CXQualType.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Basic/CXCodeGenOptions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Basic/CXDiagnostic.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Basic/CXDiagnosticIDs.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Basic/CXDiagnosticOptions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Basic/CXFileEntry.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Basic/CXFileManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Basic/CXIdentifierTable.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Basic/CXLangOptions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Basic/CXSourceLocation.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Basic/CXSourceManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Basic/CXTargetInfo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Basic/CXTargetOptions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/CodeGen/CXCodeGenAction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/CodeGen/CXModuleBuilder.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Driver/CXDriver.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Frontend/CXCompilerInstance.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Frontend/CXCompilerInvocation.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Frontend/CXFrontendOptions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Frontend/CXTextDiagnosticPrinter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Lex/CXHeaderSearch.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Lex/CXHeaderSearchOptions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Lex/CXLexer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Lex/CXPreprocessor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Lex/CXPreprocessorOptions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Lex/CXToken.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Parse/CXParseAST.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Parse/CXParser.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Sema/CXDeclSpec.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Sema/CXLookup.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Sema/CXScope.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/clang-ex/Sema/CXSema.h
)
set_target_properties(clangex PROPERTIES PUBLIC_HEADER "${pub_hdrs}")